flags: {}
packages:
  - "."
  - location:
      git: https://github.com/agrafix/hvect.git
      commit: master
      extra-dep: true
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.10.1
- ansi-terminal-0.7.1.1
- async-2.1.1.1
- call-stack-0.1.0
- colour-2.3.3
- hspec-2.4.4
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- primitive-0.6.2.0
- quickcheck-io-0.2.0
- random-1.1
- setenv-0.1.1.3
- stm-2.4.4.1
- numhask-array-0.0.2
- tf-random-0.5
resolver: nightly-2017-10-21
